apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kube-study
  name: kube-study
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-study
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-study
    spec:
      containers:
        - image: kube:latest
          name: kube-study
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 8080
status: {}